name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - uses: lablabs/setup-tflint@v1
      # Need to enable unsecure commands due to https://github.com/lablabs/setup-tflint/issues/4
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      name: Setup TFLint
      with:
        tflint_version: v0.18.0
    - name: Run tflint
      shell: bash
      run: tflint .
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Terraform fmt
      run: terraform fmt -check
    - name: Terraform validate
      run: terraform init
